"""add tables and feature toggles

Revision ID: 444b712e1faf
Revises: 9389c0ced993
Create Date: 2026-05-02 16:39:43.981864

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '444b712e1faf'
down_revision: Union[str, None] = '9389c0ced993'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photos', sa.Column('table_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'photos', 'event_tables', ['table_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'photos', type_='foreignkey')
    op.drop_column('photos', 'table_id')
    # ### end Alembic commands ###
