"""Add event features and sessions

Revision ID: 9389c0ced993
Revises: 05d080863e3d
Create Date: 2026-05-02 15:43:50.828654

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '9389c0ced993'
down_revision: Union[str, None] = '05d080863e3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('icon', sa.String(length=10), nullable=True),
    sa.Column('cover_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sessions_event_id', 'sessions', ['event_id'], unique=False)
    op.create_index('ix_access_logs_created_at', 'access_logs', ['created_at'], unique=False)
    op.add_column('events', sa.Column('is_multi_session', sa.Boolean(), nullable=False))
    op.add_column('events', sa.Column('features', sa.JSON(), nullable=False))
    op.create_index('ix_photo_guests_guest_id', 'photo_guests', ['guest_id'], unique=False)
    op.add_column('photos', sa.Column('session_id', sa.Uuid(), nullable=True))
    op.create_index('ix_photos_event_id_status', 'photos', ['event_id', 'status'], unique=False)
    op.create_index('ix_photos_session_id', 'photos', ['session_id'], unique=False)
    op.create_foreign_key(None, 'photos', 'sessions', ['session_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'photos', type_='foreignkey')
    op.drop_index('ix_photos_session_id', table_name='photos')
    op.drop_index('ix_photos_event_id_status', table_name='photos')
    op.drop_column('photos', 'session_id')
    op.drop_index('ix_photo_guests_guest_id', table_name='photo_guests')
    op.drop_column('events', 'features')
    op.drop_column('events', 'is_multi_session')
    op.drop_index('ix_access_logs_created_at', table_name='access_logs')
    op.drop_index('ix_sessions_event_id', table_name='sessions')
    op.drop_table('sessions')
    # ### end Alembic commands ###
